import type { EquationEntry } from "@/types";

export const NAV_ITEMS = [
  { label: "Home", href: "/", icon: "LayoutDashboard" },
  { label: "3D Diamond Viewer", href: "/diamond", icon: "Gem" },
  { label: "ODMR Spectroscopy", href: "/odmr", icon: "Activity" },
  { label: "Navigation Filters", href: "/filters", icon: "GitCompareArrows" },
  { label: "Magnetic Map", href: "/map", icon: "Map" },
  { label: "Equations", href: "/equations", icon: "Sigma" },
  { label: "Datasets", href: "/datasets", icon: "Database" },
  { label: "Settings", href: "/settings", icon: "Settings" },
] as const;

// Fixed <111> tetrahedral NV axes (diamond cubic), from dataset_metadata.json
export const NV_AXES: [number, number, number][] = [
  [0.5773502691896258, 0.5773502691896258, 0.5773502691896258],
  [0.5773502691896258, -0.5773502691896258, -0.5773502691896258],
  [-0.5773502691896258, 0.5773502691896258, -0.5773502691896258],
  [-0.5773502691896258, -0.5773502691896258, 0.5773502691896258],
];

export const NV_AXIS_COLORS = ["#EF4444", "#22C55E", "#3B82F6", "#EAB308"]; // red, green, blue, yellow

export const DEFAULT_API_URL = "http://localhost:8000";

export const EQUATIONS: EquationEntry[] = [
  {
    id: "eq1", number: "1", name: "ODMR Lorentzian lineshape", section: "ODMR & Sensing",
    latex: "I(f) = I_0 \\left[1 - \\sum_{k} \\frac{C_k}{1 + \\left(\\frac{f - f_k}{\\Gamma_k/2}\\right)^2}\\right]",
    explanation: "Models the photoluminescence intensity as a function of microwave frequency as a sum of Lorentzian dips, one per spin transition.",
    io: "Input: sweep frequency f, dip centers f_k, contrasts C_k, linewidths Γ_k. Output: measured intensity I(f).",
    why: "Captures the physical response of the NV ensemble to microwave driving; fitting this model recovers the resonance frequencies used for field sensing.",
    relatedPage: { label: "ODMR Spectroscopy", href: "/odmr" },
  },
  {
    id: "eq2", number: "2", name: "Two-dip peak fitting", section: "ODMR & Sensing",
    latex: "\\{\\hat I_0, \\hat f_-, \\hat f_+, \\hat C_\\pm, \\hat\\Gamma_\\pm\\} = \\arg\\min_{\\theta} \\sum_j \\left[I_j - I(f_j;\\theta)\\right]^2",
    explanation: "Nonlinear least-squares fit of the two-dip Lorentzian model to the noisy spectrum to extract the resonance frequencies f₋ and f₊.",
    io: "Input: sampled spectrum (f_j, I_j). Output: fitted resonance frequencies and uncertainties σ_f.",
    why: "Sub-linewidth precision in locating dip centers is what gives ODMR magnetometry its sensitivity, well beyond the linewidth itself.",
    relatedPage: { label: "ODMR Spectroscopy", href: "/odmr" },
  },
  {
    id: "eq3", number: "3", name: "Zeeman inversion", section: "ODMR & Sensing",
    latex: "\\hat B_\\parallel = \\frac{\\hat f_+ - \\hat f_-}{2\\gamma_e}",
    explanation: "Converts the splitting between the two ODMR resonances into a scalar magnetic field projection along the NV axis via the electron gyromagnetic ratio γₑ.",
    io: "Input: fitted frequencies f₋, f₊, constant γₑ ≈ 2.802 MHz/G. Output: scalar field projection B∥.",
    why: "This calibration-free relation removes dependence on zero-field splitting drift, since D cancels in the difference.",
    relatedPage: { label: "ODMR Spectroscopy", href: "/odmr" },
  },
  {
    id: "eq4", number: "4", name: "Vector reconstruction (least squares)", section: "Vector Reconstruction",
    latex: "\\hat{\\mathbf{B}} = \\left(\\mathbf{N}^\\top \\mathbf{W} \\mathbf{N}\\right)^{-1} \\mathbf{N}^\\top \\mathbf{W}\\, \\mathbf{b}",
    explanation: "Reconstructs the full 3D field vector in the crystal (body) frame from ≥3 scalar axis projections using weighted least squares, where N stacks the NV axis unit vectors.",
    io: "Input: projection matrix N (n_axes×3), measured projections b, weights W = diag(1/σ_f²). Output: body-frame field vector B̂.",
    why: "Combining multiple NV orientations is what enables full vector magnetometry from purely scalar ODMR measurements.",
    relatedPage: { label: "3D Diamond Viewer", href: "/diamond" },
  },
  {
    id: "eq5", number: "5", name: "Condition number of axis set", section: "Vector Reconstruction",
    latex: "\\kappa(\\mathbf{N}) = \\frac{\\sigma_{max}(\\mathbf{N})}{\\sigma_{min}(\\mathbf{N})}",
    explanation: "Quantifies how well-conditioned the chosen subset of NV axes is for vector inversion; a lower condition number means more uniform sensitivity in all directions.",
    io: "Input: axis matrix N. Output: scalar condition number κ.",
    why: "Explains why using all 4 tetrahedral axes (vs. 3 or 1) improves numerical stability and estimation accuracy.",
    relatedPage: { label: "3D Diamond Viewer", href: "/diamond" },
  },
  {
    id: "eq6a", number: "6a", name: "NV axis orientation (tetrahedral)", section: "Vector Reconstruction",
    latex: "\\cos^{-1}\\left(-\\tfrac{1}{3}\\right) \\approx 109.47^{\\circ}",
    explanation: "The four <111> NV axes in the diamond lattice are separated by the tetrahedral angle, fixed by crystal symmetry and identical for every NV center.",
    io: "Input: crystal symmetry (diamond cubic, Fd3̄m). Output: pairwise axis angle ≈ 109.5°.",
    why: "This fixed geometry is exactly why the sensor is 'calibration-free': the axis directions never drift and need no per-device calibration.",
    relatedPage: { label: "3D Diamond Viewer", href: "/diamond" },
  },
  {
    id: "eq6b", number: "6b", name: "Single-axis projection path", section: "Vector Reconstruction",
    latex: "\\hat B_\\parallel^{(1)} = \\hat{\\mathbf b}\\cdot \\hat{\\mathbf n}_1",
    explanation: "When only one NV axis is used (axis_count = 1), the reconstruction reduces to the single measured scalar projection with no matrix inversion.",
    io: "Input: single fitted projection b, axis n₁. Output: scalar field along n₁ only.",
    why: "Serves as the low-complexity baseline against which 3- and 4-axis reconstruction is compared.",
    relatedPage: { label: "ODMR Spectroscopy", href: "/odmr" },
  },
  {
    id: "eq7", number: "7", name: "Body-to-world rotation", section: "Frame Rotation & Map",
    latex: "\\mathbf{B}_{world,xy} = \\mathbf{R}(\\psi)\\,\\mathbf{B}_{body,xy}, \\quad \\mathbf{R}(\\psi)=\\begin{bmatrix}\\cos\\psi & -\\sin\\psi\\\\ \\sin\\psi & \\cos\\psi\\end{bmatrix}",
    explanation: "Rotates the reconstructed horizontal field components from the sensor/body frame into the fixed world (map) frame using the current heading estimate ψ.",
    io: "Input: body-frame B_xy, heading ψ. Output: world-frame B_xy.",
    why: "The magnetic anomaly map is stored in world coordinates, so field readings must be rotated before they can be compared to it.",
    relatedPage: { label: "Magnetic Map", href: "/map" },
  },
  {
    id: "eq8", number: "8", name: "Bilinear map interpolation", section: "Frame Rotation & Map",
    latex: "M(x,y) = (1-u)(1-v)M_{i,j} + u(1-v)M_{i+1,j} + (1-u)v M_{i,j+1} + uv\\, M_{i+1,j+1}",
    explanation: "Interpolates the gridded magnetic anomaly map at an arbitrary continuous position (x, y) using the four surrounding grid cells.",
    io: "Input: grid values M, fractional offsets u, v within the cell. Output: interpolated field magnitude at (x, y).",
    why: "Enables smooth, differentiable measurement predictions at any particle/state position, not just discrete grid points.",
    relatedPage: { label: "Magnetic Map", href: "/map" },
  },
  {
    id: "eq9", number: "9", name: "Correlation map-matching score", section: "Map Matching",
    latex: "\\rho(\\mathbf{r}) = \\frac{\\sum_k \\big(z_k - \\bar z\\big)\\big(M(\\mathbf{r}+\\Delta \\mathbf{r}_k) - \\bar M\\big)}{\\sqrt{\\sum_k (z_k-\\bar z)^2}\\sqrt{\\sum_k (M(\\cdot)-\\bar M)^2}}",
    explanation: "Cross-correlates a short window of measured field magnitudes against candidate map patches (shifted by the dead-reckoned relative path) to score positional hypotheses.",
    io: "Input: measurement window z_k, IMU-derived relative offsets Δr_k, candidate map window M. Output: correlation score ρ ∈ [-1, 1].",
    why: "Provides a coarse, calibration-free position initialization without needing GPS, by matching the shape of the measured field trace to the map.",
    relatedPage: { label: "Magnetic Map", href: "/map" },
  },
  {
    id: "eq10", number: "10", name: "Best-match initialization", section: "Map Matching",
    latex: "\\hat{\\mathbf r}_{init} = \\arg\\max_{\\mathbf r \\in \\text{grid}} \\rho(\\mathbf r)",
    explanation: "Selects the grid location with the highest correlation score as the initial position estimate fed to the EKF/PF.",
    io: "Input: correlation surface ρ(r) over a coarse search grid. Output: initial position r̂_init.",
    why: "Good initialization is critical for both EKF linearization validity and particle filter sample efficiency.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq11", number: "11", name: "State vector", section: "EKF",
    latex: "\\mathbf{x} = \\begin{bmatrix} x & y & v_x & v_y & \\psi \\end{bmatrix}^\\top",
    explanation: "Five-dimensional state comprising 2D position, 2D velocity, and heading.",
    io: "Input: —. Output: state definition used throughout EKF/PF.",
    why: "A minimal state that captures the navigation-relevant kinematics while keeping the filter tractable in real time.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq12", number: "12", name: "IMU-driven motion model", section: "EKF",
    latex: "\\mathbf{x}_{k+1} = f(\\mathbf{x}_k, \\mathbf{u}_k) = \\mathbf{x}_k + \\begin{bmatrix} v_x \\Delta t \\\\ v_y \\Delta t \\\\ a_x \\Delta t \\\\ a_y \\Delta t \\\\ \\omega \\Delta t \\end{bmatrix}",
    explanation: "Propagates the state forward using IMU-measured accelerations (a_x, a_y) and angular rate ω over timestep Δt.",
    io: "Input: state x_k, IMU input u_k = (a_x, a_y, ω). Output: predicted next state x_{k+1}.",
    why: "Dead-reckoning between magnetic updates; drives the EKF prediction step.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq13", number: "13", name: "State transition Jacobian", section: "EKF",
    latex: "\\mathbf{F}_k = \\left.\\frac{\\partial f}{\\partial \\mathbf{x}}\\right|_{\\mathbf{x}_k, \\mathbf{u}_k}",
    explanation: "Linearizes the (nearly linear) motion model about the current state estimate for covariance propagation.",
    io: "Input: current state, motion model f. Output: 5×5 Jacobian F_k.",
    why: "Required by the extended Kalman filter to propagate uncertainty through a (mildly) nonlinear model.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq14", number: "14", name: "Covariance prediction", section: "EKF",
    latex: "\\mathbf{P}_{k+1}^{-} = \\mathbf{F}_k \\mathbf{P}_k \\mathbf{F}_k^\\top + \\mathbf{Q}_k",
    explanation: "Propagates the state covariance forward through the prediction step, inflating it by the process noise Q_k.",
    io: "Input: P_k, F_k, Q_k. Output: predicted covariance P⁻.",
    why: "Growth of uncertainty between magnetic updates directly determines how much the correction step must trust the measurement.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq15", number: "15", name: "Process noise covariance", section: "EKF",
    latex: "\\mathbf{Q}_k = \\mathrm{diag}\\!\\left(\\sigma_a^2\\tfrac{\\Delta t^4}{4}, \\sigma_a^2\\tfrac{\\Delta t^4}{4}, \\sigma_a^2\\Delta t^2, \\sigma_a^2\\Delta t^2, \\sigma_g^2\\Delta t^2\\right)",
    explanation: "Derives process noise directly from datasheet IMU noise densities (accel σ_a, gyro σ_g), scaled by a tunable process_noise_scale.",
    io: "Input: IMU noise densities, Δt, scale factor. Output: 5×5 Q matrix.",
    why: "Ties filter tuning to physically meaningful sensor specifications rather than arbitrary hand-tuned constants.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq16", number: "16", name: "Measurement model", section: "EKF",
    latex: "z_k = h(\\mathbf{x}_k) + v_k = M\\big(x_k, y_k\\big) + v_k",
    explanation: "The scalar magnetic field magnitude at the current position, read from the interpolated map (Eq. 8), plus measurement noise.",
    io: "Input: position (x_k, y_k), map M. Output: predicted scalar measurement.",
    why: "Directly links the filter state to the magnetic map, which is the sole source of drift-free position information.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq17", number: "17", name: "Measurement Jacobian & innovation", section: "EKF",
    latex: "\\mathbf{H}_k = \\left.\\frac{\\partial h}{\\partial \\mathbf{x}}\\right|_{\\mathbf{x}_k^{-}}, \\qquad y_k = z_k - h(\\mathbf{x}_k^{-})",
    explanation: "Linearizes the map measurement function (via its spatial gradient) and computes the innovation between predicted and observed field.",
    io: "Input: predicted state x⁻, map gradient. Output: H_k, innovation y_k.",
    why: "The map gradient in H_k governs observability: flat map regions give little correction signal.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq18", number: "18", name: "Kalman gain & update", section: "EKF",
    latex: "\\mathbf{K}_k = \\mathbf{P}_k^{-}\\mathbf{H}_k^\\top\\big(\\mathbf{H}_k\\mathbf{P}_k^{-}\\mathbf{H}_k^\\top + R_k\\big)^{-1}, \\quad \\mathbf{x}_k = \\mathbf{x}_k^{-} + \\mathbf{K}_k y_k",
    explanation: "Computes the optimal blending gain between prediction and measurement, then corrects the state estimate.",
    io: "Input: P⁻, H_k, R_k, innovation y_k. Output: Kalman gain K_k, corrected state x_k.",
    why: "The core correction step that pulls dead-reckoned drift back toward the magnetic map.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq19", number: "19", name: "Normalized innovation squared (NIS)", section: "EKF",
    latex: "\\mathrm{NIS}_k = y_k^\\top S_k^{-1} y_k, \\quad S_k = \\mathbf{H}_k\\mathbf{P}_k^{-}\\mathbf{H}_k^\\top + R_k",
    explanation: "A consistency statistic comparing the actual innovation to its predicted covariance S_k; used to validate filter tuning.",
    io: "Input: innovation y_k, innovation covariance S_k. Output: scalar NIS_k.",
    why: "NIS staying near its expected value (≈ degrees of freedom) is the standard diagnostic for a well-tuned EKF.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq20", number: "20", name: "Particle set representation", section: "Particle Filter",
    latex: "\\{\\mathbf{x}^{(i)}_k, w^{(i)}_k\\}_{i=1}^{N}, \\qquad \\sum_i w_k^{(i)} = 1",
    explanation: "Represents the posterior belief as a weighted set of N particles, each a full state hypothesis with an associated weight.",
    io: "Input: N (n_particles). Output: particle set at time k.",
    why: "Enables representing arbitrarily non-Gaussian, multi-modal beliefs — useful in ambiguous or repetitive map regions.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq21", number: "21", name: "Particle propagation", section: "Particle Filter",
    latex: "\\mathbf{x}^{(i)}_{k+1} = f\\big(\\mathbf{x}^{(i)}_k, \\mathbf{u}_k\\big) + \\boldsymbol{\\epsilon}^{(i)}_k, \\quad \\boldsymbol{\\epsilon}^{(i)}_k \\sim \\mathcal N(0, \\mathbf{Q}_k)",
    explanation: "Each particle is propagated through the same IMU motion model as the EKF, with independently sampled process noise added.",
    io: "Input: particle state, IMU input, Q_k. Output: propagated particle.",
    why: "Injecting per-particle noise maintains sample diversity needed to represent the posterior after resampling.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq22", number: "22", name: "Weight update (likelihood)", section: "Particle Filter",
    latex: "w_k^{(i)} \\propto w_{k-1}^{(i)} \\cdot \\exp\\!\\left(-\\frac{\\big(z_k - M(x_k^{(i)}, y_k^{(i)})\\big)^2}{2\\sigma_{meas}^2}\\right)",
    explanation: "Re-weights each particle by the Gaussian likelihood of the observed magnetic field given that particle's predicted map reading.",
    io: "Input: measurement z_k, particle position, map M, σ_meas. Output: updated (unnormalized) weight.",
    why: "Particles sitting on map regions consistent with the measurement gain weight; inconsistent ones are suppressed.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq23", number: "23", name: "Effective sample size", section: "Particle Filter",
    latex: "N_{eff} = \\frac{1}{\\sum_i \\big(w_k^{(i)}\\big)^2}",
    explanation: "Estimates how many particles are effectively contributing to the posterior, given weight degeneracy.",
    io: "Input: normalized weights w^{(i)}_k. Output: scalar N_eff ∈ [1, N].",
    why: "Triggers resampling when N_eff falls below a threshold, preventing weight collapse onto a single particle.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
  {
    id: "eq24", number: "24", name: "Systematic resampling", section: "Particle Filter",
    latex: "\\text{if } N_{eff} < N_{thresh}: \\quad \\{\\mathbf{x}^{(i)}\\} \\leftarrow \\text{resample}\\big(\\{\\mathbf{x}^{(i)}, w^{(i)}\\}\\big), \\ w^{(i)} \\leftarrow \\tfrac1N",
    explanation: "Draws a new particle set proportional to the current weights and resets all weights to uniform, focusing computation on high-likelihood regions.",
    io: "Input: particle set, weights, resample_threshold. Output: resampled particle set with uniform weights.",
    why: "Prevents particle degeneracy, keeping the filter statistically efficient over long trajectories.",
    relatedPage: { label: "Navigation Filters", href: "/filters" },
  },
];
